# Generated by Django 4.1.5 on 2023-01-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidences',
            options={'verbose_name_plural': 'Incidences'},
        ),
    ]
