# Generated by Django 4.1.5 on 2023-01-30 15:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_alter_incidences_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('yatayat', models.CharField(max_length=20)),
                ('bus_image', models.ImageField(default='busdefault.png', upload_to='')),
            ],
        ),
    ]
